### ISSUE TITLE
Are we focused on final products, or on general libraries/plugins/etc ?

### ISSUE THREAD

**Issue by swoogles** [ShoulderStanders/InitialDiscussion#3]
We can build entire standalone applications, or we can focus on modules to be used in larger ecosystems.

**Comment by BruceEckel** [comment]
I don't know whether we need to specify that at this point. Personally I am more interested in creating new things rather than maintaining someone else's software. But the "Evolutionary Purpose" part of a Teal organization means that it can go where it needs to go.

**Comment by swoogles** [comment]
Yeah, I'll consider this one a cart-before-the-horse
